services:
  app:
    build:
      context: ../..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspace:cached
    command: sleep infinity
    networks:
      - iceberg
  
networks:
  iceberg:
    driver: bridge

