services:
  app:
    build:
      context: ../..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspace:cached
    command: sleep infinity
    networks:
      - iceberg
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 12G
  
networks:
  iceberg:
    driver: bridge

