services:
  postgres:
    image: postgres:14
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=nessie
      - POSTGRES_PASSWORD=nessie
      - POSTGRES_DB=trade_db
    networks:
      - iceberg
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nessie"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  iceberg:
    driver: bridge