dbt_trade:
  target: dev
  outputs:
    dev:
      type: dremio
      user: admin
      password: password-9
      software_host: dremio
      port: 9047
      object_storage_source: nessie
      threads: 2
      use_ssl: false
    target: dev
