{{ config(
    materialized='table',
    on_schema_change = 'ignore',
    format='iceberg',
    schema='silver'
) }}
SELECT
    CASE WHEN NULLIF(PORT, '-') IS NOT NULL THEN CAST(PORT AS INT) ELSE NULL END AS PORT,
    CASE WHEN NULLIF(CTY_CODE, '-') IS NOT NULL THEN CAST(CTY_CODE AS INT) ELSE NULL END AS CTY_CODE,
    CAST(I_COMMODITY AS INT) AS I_COMMODITY,
    I_COMMODITY_SDESC,
    CAST(GEN_VAL_MO AS DOUBLE) AS ALL_VAL_MO,
    CAST(AIR_VAL_MO AS DOUBLE) AS AIR_VAL_MO,
    CAST(AIR_WGT_MO AS DOUBLE) AS AIR_WGT_MO,
    CAST(VES_VAL_MO AS DOUBLE) AS VES_VAL_MO,
    CAST(VES_WGT_MO AS DOUBLE) AS VES_WGT_MO,
    SUMMARY_LVL,
    COMM_LVL,
    CAST("YEAR" AS INT) AS IMPORT_YEAR,
    CAST("MONTH" AS INT) AS IMPORT_MONTH
    -- CAST("LAST_UPDATE" AS DATE) AS LAST_UPDATE
    -- CASE WHEN NULLIF(LAST_UPDATE, '0') IS NOT NULL THEN CAST(LAST_UPDATE AS DATE) ELSE NULL END AS LAST_UPDATE
FROM trade."import".port_lvl_data