{{ config(
    materialized='table',
    on_schema_change = 'ignore',
    format='iceberg',
    schema='silver',
    partition_by=['bucket(32, CTY_NAME)', 'EXPORT_YEAR']
) }}
SELECT
    CASE WHEN NULLIF(PORT, '-') IS NOT NULL THEN CAST(PORT AS INT) ELSE NULL END AS PORT,
    CASE WHEN NULLIF(CTY_CODE, '-') IS NOT NULL THEN CAST(CTY_CODE AS INT) ELSE NULL END AS CTY_CODE,
    CTY_NAME,
    CAST(E_COMMODITY AS INT) AS E_COMMODITY,
    E_COMMODITY_SDESC,
    CAST(ALL_VAL_MO AS DOUBLE) AS ALL_VAL_MO,
    CAST(AIR_VAL_MO AS DOUBLE) AS AIR_VAL_MO,
    CAST(AIR_WGT_MO AS DOUBLE) AS AIR_WGT_MO,
    CAST(VES_VAL_MO AS DOUBLE) AS VES_VAL_MO,
    CAST(VES_WGT_MO AS DOUBLE) AS VES_WGT_MO,
    SUMMARY_LVL,
    COMM_LVL,
    CAST("YEAR" AS INT) AS EXPORT_YEAR,
    CAST("MONTH" AS INT) AS EXPORT_MONTH
    -- CASE WHEN NULLIF(LAST_UPDATE, '0') IS NOT NULL THEN CAST(LAST_UPDATE AS DATE) ELSE NULL END AS LAST_UPDATE
    -- 0, 127 WERE THE TWO DISTINCT VALUES FOR LAST_UPDATE
FROM trade.export.port_lvl_data