name: CI Pipeline
on:
  push:
    branches: [ feature/winpc ]
  pull_request:
    branches: [ feature/winpc ]
jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install quality tools
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Check code formatting
      run: |
        isort src/ tests/ 
        black src/ tests/
    
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: quality

    env:
      DREMIO_USER: ${{ secrets.DREMIO_USER }}
      DREMIO_PASSWORD: ${{ secrets.DREMIO_PASSWORD }}
      DREMIO_DB: ${{ secrets.DREMIO_DB }}
      DREMIO_HOST: ${{ secrets.DREMIO_HOST }}
      DREMIO_PORT: ${{ secrets.DREMIO_PORT }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q
  